In [1]:
import numpy as np

In [2]:
def compute_vector_length(vector):
    return np.linalg.norm(vector)

In [3]:
def compute_dot_product(vector1, vector2):
    return np.dot(vector1, vector2)

In [4]:
def matrix_multi_vector(matrix, vector):
    return np.dot(matrix, vector)


In [5]:
def matrix_multi_matrix(matrix1, matrix2):
    return matrix1 @ matrix2


### **Inverse matrix**

* Matrix A:

$$A = \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}$$

where A ∈ R²×² (A is a 2x2 matrix in real numbers).

* Determinant of A ∈ R²×²:

$$det(A) = ad - bc$$

* If det(A) ≠ 0, then A is invertible. Its inverse is denoted by A⁻¹ and is given by:

$$A^{-1} = \frac{1}{det(A)} \begin{pmatrix}
d & -b \\
-c & a
\end{pmatrix}$$

In [10]:
def inverse_matrix(matrix):
    determinant = np.linalg.det(matrix)
    if determinant == 0:
        raise ValueError("Matrix is not invertible")
    inverse = np.linalg.inv(matrix)
    return inverse

A = np.array([-2, 6, 8, -4]).reshape(2, 2)
print(inverse_matrix(A))

[[0.1  0.15]
 [0.2  0.05]]


### **Eigenvector and Eigenvalue**
* A ∈ R<sup>n</sup>×<sup>n</sup>
I (identity matrix) ∈ R<sup>n</sup>×<sup>n</sup>,
v ∈ R<sup>n</sup>
* Eigenvalue (λ): det(A - λI) = 0
* Eigenvector (v): Av = λv or (A - λI)v = 0
* Normalize vector:$$
\frac {v}{||v||}, \quad vi = \frac{vi}{\sqrt{\sum_{i=1}^{n} vi^2}}
$$

In [11]:
def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    normalized_eigenvectors = eigenvectors / np.linalg.norm(eigenvectors, axis=1).reshape(-1, 1)
    return eigenvalues, normalized_eigenvectors

B = np.array([0.9, 0.2, 0.1, 0.8]).reshape(2, 2)
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(B)
print(eigenvalues)
print(eigenvectors)

[1.  0.7]
[[ 0.78446454 -0.62017367]
 [ 0.53452248  0.84515425]]


### **Cosine Similarity**
$$
\text{Data (vector } x, y): \quad x = \{x_1, ..., x_N\} \quad y = \{y_1, ..., y_N\} \\ \\
\text{Cosine Similarity: } \quad cs(x, y) = \frac{x.y}{||x|| \, ||y||} = \frac{\sum_{i=1}^{n} x_i y_i}{\sqrt{\sum_{i=1}^{n} x_i^2} \sqrt{\sum_{i=1}^{n} y_i^2}}
$$

In [12]:
def compute_cosine(vector1, vector2):
    dot_product = np.dot(vector1, vector2)
    vector1_length = np.linalg.norm(vector1)
    vector2_length = np.linalg.norm(vector2)
    return dot_product / (vector1_length * vector2_length)

x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
print(compute_cosine(x, y))

0.5773502691896257


In [16]:
x = np. array ([[ -1 , 2] ,[3 , -4]])
k = np. array ([1 , 2])
print ('result \n', x@k )

result 
 [ 3 -5]


In [17]:
m = np. array ([[ -1 , 1 , 1] , [0 , -4 , 9]])
v = np. array ([0 , 2 , 1])
result = matrix_multi_vector (m, v)
print ( result )

[3 1]


In [18]:
m1 = np. array ([[0 , 1 , 2] , [2 , -3 , 1]])
m2 = np. array ([[1 , -3] ,[6 , 1] , [0 , -1]])
result = matrix_multi_matrix (m1 , m2)
print ( result )

[[  6  -1]
 [-16 -10]]


In [20]:
m1 = np.eye (3)
m2 = np. array ([[1 , 1 , 1] ,[2 , 2 , 2] , [3 , 3 , 3]])
result = m1@m2
print ( result )

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [21]:
m1 = np.eye (2)
m1 = np. reshape (m1 ,( -1 ,4) ) [0]
m2 = np. array ([[1 , 1 , 1 , 1] ,[2 , 2 , 2 , 2] , [3 , 3 , 3 , 3] , [4 , 4 , 4 , 4]])
result = m1@m2
print ( result )

[5. 5. 5. 5.]


In [22]:
m1 = np. array ([[1 , 2] , [3 , 4]])
m1 = np. reshape (m1 ,( -1 ,4) , "F") [0]
m2 = np. array ([[1 , 1 , 1 , 1] ,[2 , 2 , 2 , 2] , [3 , 3 , 3 , 3] , [4 , 4 , 4 , 4]])
result = m1@m2
print ( result )

[29 29 29 29]


In [23]:
m1 = np. array ([[ -2 , 6] , [8 , -4]])
result = inverse_matrix (m1)
print ( result )

[[0.1  0.15]
 [0.2  0.05]]


In [24]:
matrix = np. array ([[0.9 , 0.2] , [0.1 , 0.8]])
eigenvalues , eigenvectors = compute_eigenvalues_eigenvectors ( matrix )
print ( eigenvectors )

[[ 0.78446454 -0.62017367]
 [ 0.53452248  0.84515425]]


In [25]:
x = np. array ([1 , 2 , 3 , 4])
y = np. array ([1 , 0 , 3 , 0])
result = compute_cosine (x,y)
print ( round (result , 3) )

0.577
